apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: flask-app
  labels:
    app: flask-frontend
spec:
  type: ClusterIP
  selector:
    app: flask-frontend
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
